# Infra/monitor_weekly.yaml

trigger: none

schedules:
  - cron: "0 6 * * SUN"   # every Sunday 06:00 UTC
    displayName: Weekly Summary Monitor
    branches:
      include:
        - uat
        - prod
    always: true

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    type: string
    default: 'uat'
    values:
      - uat
      - prod

steps:
- script: |
    echo "Invoke weekly monitor for ${{ parameters.environment }}"
    aws lambda invoke \
      --function-name monitorlambda-${{ parameters.environment }} \
      --payload '{"mode": "weekly", "days": 7 }' \
      --region eu-west-1 output.json
    cat output.json
  displayName: 'Invoke Weekly Monitor Lambda'
  env:
    AWS_REGION: 'eu-west-1'
