#Infra/monitor_invoke.yaml

trigger: none

# Uncomment schedule block when you want it scheduled
# schedules:
#   - cron: "0 3 * * *"  # daily at 03:00 UTC - enable later if you want
#     displayName: Daily Monitor
#     branches:
#       include:
#         - uat
#         - prod
#     always: true

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    type: string
    default: 'uat'
    values:
      - uat
      - prod

variables:
  AWS_REGION: 'eu-west-1'    # change if you run lambda in different region
  LAMBDA_NAME: ${{ format('monitorlambda-{0}', parameters.environment) }}

steps:
- checkout: none

- task: ShellScript@2
  displayName: 'Invoke Monitor Lambda and capture output'
  inputs:
    scriptPath: inline
    script: |
      set -euo pipefail
      echo "Invoking Lambda: ${LAMBDA_NAME} in ${AWS_REGION}"
      aws lambda invoke \
        --function-name "${LAMBDA_NAME}" \
        --payload '{"mode":"daily"}' \
        --region ${AWS_REGION} output.json || true
      echo "---- output.json ----"
      cat output.json || true
      # extract discrepancies to text file for artifact
      python3 - <<'PY'
import json, sys
try:
    j = json.load(open('output.json'))
except Exception as e:
    print("Failed to parse output.json:", e)
    j = {}
dis = j.get('discrepancies', [])
with open('missing_files.txt','w') as f:
    if not dis:
        f.write("NO_DISCREPANCIES\n")
    else:
        for d in dis:
            f.write(d + "\n")
print("Wrote missing_files.txt with", len(dis), "entries")
PY

- task: PublishBuildArtifacts@1
  displayName: 'Publish monitor artifacts (output.json, missing_files.txt)'
  inputs:
    PathtoPublish: |
      output.json
      missing_files.txt
    ArtifactName: monitor-reports
    publishLocation: Container
